[package]
name = "rget"
version = "0.1.0"
authors = ["Andrew Murray <darbyguitars@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.26.0"
indicatif = "0.13.0"
console = "0.9.1"
reqwest = "0.9.22"